-- Creates carrier table
CREATE TABLE carrier (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID())),
  code VARCHAR(40) NOT NULL,
  name VARCHAR(160) NOT NULL,
  carrier_type ENUM('TRANSPORTADORA','AGREGADO') NOT NULL,
  doc_number VARCHAR(20) NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_carrier__uuid (uuid),
  UNIQUE KEY uk_carrier__code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
